/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class realHTML_tomcat_connector_JNINatural */

#ifndef _Included_realHTML_tomcat_connector_JNINatural
#define _Included_realHTML_tomcat_connector_JNINatural
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_callNatural
 * Signature: (LrealHTML/tomcat/connector/RH4NParams;[LrealHTML/tomcat/environment/EnvironmentVar;LrealHTML/tomcat/JSONMatcher/LLHandler;)LrealHTML/tomcat/connector/RH4NReturn;
 */
JNIEXPORT jobject JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1callNatural
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_printVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1printVersion
  (JNIEnv *, jobject);

/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_dumpVars
 * Signature: (LrealHTML/tomcat/JSONMatcher/LLHandler;)I
 */
JNIEXPORT jint JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1dumpVars
  (JNIEnv *, jobject, jobject);

/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_passwd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1passwd
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
